### ISSUE TITLE
Something wrong with data send back

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#19] opened 2019-04-13 11:48 UTC
Hello,
I've asked you how to send data back when board receives an interest,actually,I just implemented sending interest from Android to board, when board receives the interest,on interest function will send data back,I set LED4 blink once data is sent from board.As a result, LED4 did blinked, but I didn't get any log information about the content of data on Android Studio.We assumed that maybe something wrong with Android receiving data packet or data packet definition on board.I don't know what wrong with this case,that will be great if you can provide me some help.

**Comment by Heath68** [comment] 2019-04-13 14:13
I found that there is no decode data packet process,is it because Android didn't decode the received data?

**Comment by peurpdapeurp** [comment] 2019-04-13 15:58
The decoding of data packets can be done with the jndn library, which is the Java library for NDN (the ndn-lite-support library actually depends on jndn).

The API's you are looking for are here: https://github.com/named-data/jndn/blob/master/src/net/named_data/jndn/Data.java

The big idea is this: you should get the raw bytes of the data packet the Android phone receives, create a Blob object using those raw bytes (let's call it data_blob), and then create a new Data object (let's call it new_data) and call new_data.wireDecode(data_blob).

**Comment by Heath68** [comment] 2019-04-15 08:54
I put the code of show received data code in NDN-IOT-Android as follow: 
```       private class incomingData implements OnData{
            @Override
            public void onData(Interest interest, Data data) {
                Log.i(TAG, "Got data packet with name:" + data.getName().toUri());
                String msg = data.getContent().toString();
                Log.i(TAG, "onData: " + msg);
                if (msg.length() == 0) {
                    Log.i(TAG, "Data is null");
                } else if (msg.length() > 0) {
                    comeBackData.setContent(data.getContent());
                }
            }
        }                              ```


But I don't understand how to use jndn to decode the data and what is the usage of onData function.

**Comment by Heath68** [comment] 2019-04-15 09:08
And how to get the raw bytes of the data packet the Android phone receives.

**Comment by peurpdapeurp** [comment] 2019-04-15 16:16
Ah, I may have misled you in my earlier post, apologies.

You actually do not have to get the raw bytes of the data and decode them; this is something that the ndn-lite android support library already does for you through its BLEFace.

You just have to do the following (also, I will reference line numbers in the NDN-IoT Android example main activity, here https://github.com/gujianxiao/NDN-IoT-Android/blob/4a3f0df75ddb9f5a21bde8542d45e72f965b03df/app/src/main/java/com/example/chenbo/helloworld/MainActivity.java)

1) Create an onData callback object (just like at line 380).

2) Create an interest with the appropriate name (just like at line 427)

3) Use your BLE Face object and call BLEFace.expressInterest with your interest and onData callback (just like at line 430)

**Comment by Heath68** [comment] 2019-04-16 02:51
I think there still is something wrong with board sending interest process. The code of on interest in board to send data back is in this issue:https://github.com/gujianxiao/ndn-lite-application-for-nRF52840-BLE_version/issues/1
I checked log information and found that whether I send interest from another board or from Android,the onData function of them weren't triggered.That was really confusing.I don't know what wrong with send data back process.

**Comment by Heath68** [comment] 2019-04-16 02:54
Also I checked return of ndn_forwarder_put_data(),there was nothing wrong with it.

**Comment by peurpdapeurp** [comment] 2019-04-16 05:11
I think this may be an issue with the code; I actually do not remember ever testing sending an interest from the Android to the board, so I will test the code for this tomorrow and leave an update to this issue once I get it working (I will also upload example code)

**Comment by peurpdapeurp** [comment] 2019-04-17 04:59
Apologies, I underestimated the time it would take me to get this working again.

I think it is more likely that I will have some updates for you / example code by the end of the week.

**Comment by peurpdapeurp** [comment] 2019-04-19 05:13
The Android example has been updated to be simpler. The next step is to test sending the interest from Android to board; that will likely be done by the end of this weekend / the beginning of next week.

**Comment by Heath68** [comment] 2019-04-19 07:04
I found some thing wrong with send data from board to Android in forwarder API:https://github.com/named-data-iot/ndn-lite/blob/58a96e73293d488899c9cfc82caaba490705d792/forwarder/forwarder.c
ndn_face_send()didn't work at all,turned out that face=NULL.
```static ndn_bitset_t
fwd_multicast(uint8_t* packet,
              size_t length,
              ndn_bitset_t out_faces,
              ndn_table_id_t in_face)
{ APP_LOG("3333333333333333\n");
  ndn_table_id_t id;
  ndn_face_intf_t* face;
  ndn_bitset_t ret = 0;

  while(out_faces != 0){
    id = bitset_pop_least(&out_faces);
    APP_LOG("slots id:%d\n inface:%#X\n",id,in_face);
    face = forwarder.facetab->slots[id];
    if(id != in_face && face != NULL){
      ndn_face_send(face, packet, length);
      ret = bitset_set(ret, id);
    }
//    else if(face==NULL){
//    APP_LOG("face==NULL!!!!!!!!!!!!!!\n");}
  return ret;
    }
}

**Comment by peurpdapeurp** [comment] 2019-04-22 05:01
Thank you for bringing up that issue; I do not fully understand what it means, but I will try to investigate.

I have been trying to get an example working to have interest / data exchange between the phone and a board. I have gotten an interest to be sent from the phone to the board successfully after onboarding, but I am running into an issue with the sha function of the ndn-lite library; that is what I am looking into now.

I also did a test earlier and successfully sent an interest from the board to the phone after onboarding; essentially the main things that I have left to see work is sending data from the board to the phone, and sending data from the phone to the board.

I would update the code of the example, but unfortunately the code is not working properly for me right now, so I will not upload it until I get it working.

Additionally, I think I should warn that I will likely not have as much time to spend on fixing the application over the next week; I will probably not be able to spend much time on this until next weekend.

For now, in case you would like to work off of the code that I am working on right now, I have uploaded it to another repository here: https://github.com/peurpdapeurp/temporary-ndn-lite-nrf52840-ble-example

**Comment by Heath68** [comment] 2019-04-22 05:21
We found the reason boards cannot sent data to Android is that in forwarder API,ndn_face_send() was never been executed,that means face=NULL.
In forwarder API,face = forwarder.facetab->slots[id];we think there is something wrong with the face in facetab.

**Comment by Heath68** [comment] 2019-04-22 05:23
Sorry I don't understand what you mean,do you mean there is still some problem with sending data from board to Android?

**Comment by peurpdapeurp** [comment] 2019-04-22 05:25
I am not sure yet; I was trying to test that by having the phone send an interest to the board and having the board respond with a data packet, but I ran into an issue with the ndn-lite library's security backend which stopped me from even creating the data packet on the board side.

I am quite sure the issue is related to the security backend not setting the sha256 digest functions of the ndn-lite library properly, which causes the program on the nRF52840 board to crash when it gets to my call to ndn_data_tlv_encode, but I will have to investigate more later.

**Comment by peurpdapeurp** [comment] 2019-04-23 05:43
I thought I should leave an update, since you are waiting on me to fix the issue.

I realized through some debugging that the problem I'm having was just a stupid mistake on my part; I did not initialize the name of the data packet I was trying to encode, which was causing the crash.

I am currently in the process of fixing it, although I am now stuck on a TLV decoding issue.

The problem I'm fixing now is that the interest I send from the phone to the board with the hex code

05230717080570686F6E650804746573740808696E746572657374090212000A046DEC4A86

is failing the call to ndn_interest_from_block with a return value of -12 (wrong tlv type).

I am going to look into this issue at the next chance I get.

Unfortunately, I have to be firm about the fact that I definitely cannot promise to work on this over the next few days. I am falling behind on my classwork / labwork. I am sorry for the delays, but I need to catch up on my other work.

In the mean time, I have pushed the updated example code I have gotten to the same temporary repository I mentioned before; you can find it here: https://github.com/peurpdapeurp/temporary-ndn-lite-nrf52840-ble-example

**Comment by peurpdapeurp** [comment] 2019-04-27 21:54
Just to give an update here: I've found through some debugging that the TLV decoding issue may be related to a problem in the jNDN library. I have created a bug report here (https://redmine.named-data.net/issues/4925), and am waiting for the response.

**Comment by peurpdapeurp** [comment] 2019-04-29 06:24
Another update, I've found that the issue is actually probably on the ndn-lite libary side rather than the jndn library. I will post another update tomorrow.

**Comment by peurpdapeurp** [comment] 2019-04-29 16:55
Another update, I've fixed the issue related to the handling of deprecated NDN packet format in ndn-lite, and am now working on addressing the issue with the null face that was brought up by Heath earlier.

**Comment by peurpdapeurp** [comment] 2019-05-05 17:19
An update: I have fixed the issue related to data forwarding in the ndn-lite library; it had to do with me setting the face_id of the ndn_nrf_ble_face incorrectly. The data can now be transmitted to the Android phone.

The problem now is that the Android phone is failing to decode the data sent from the board. I am working on fixing this now.

**Comment by peurpdapeurp** [comment] 2019-05-05 17:52
An update, through some debugging have found that the issue is related to the data packet generated by the ndn-lite library not having a metainfo tlv block. I think this should be okay, since in the data packet specification the metainfo block is optional (https://named-data.net/doc/NDN-packet-spec/current/data.html), but it seems possible that the jndn library forces this metainfo block to be there. I think this is still likely some mistake on my part, but I have created an issue here (https://redmine.named-data.net/issues/4926). I will come back to this later today.

**Comment by peurpdapeurp** [comment] 2019-05-06 15:09
As a temporary fix, I've added code into the BLE example that adds a metainfo tlv block to the data packet encoding (by setting its freshness period). This has let the Android application successfully decode the data. I am quite sure now that this is a bug in the jndn libary, so I will wait for a response to (https://redmine.named-data.net/issues/4926). However, I think that at this point the issue on the ndn-lite library side is fixed, so I will close this issue.

**Closed as completed by peurpdapeurp** 2019-05-06 15:09 UTC
